version: '2.0'

services:
  client:
    image: nginx:alpine
    ports:
      - 5000:80
    volumes:
      - ./client:/usr/share/nginx/html:ro

  cdn:
    build: ./cdn
    environment:
      - JWT_SECRET
    ports:
      - 5001:80
    volumes:
      - ./cdn/pub:/usr/share/nginx/html:ro
