version: '2'

services:
  web:
    build: ./web
    ports:
      - 5000:80
    volumes:
      - cached:/var/www/cached
    depends_on:
      - resizer
      - cache

  resizer:
    build: ./resizer
    environment:
      - SECRET
    volumes:
      - ./resizer/uploaded:/var/www/uploaded

  cache:
    build: ./cache

volumes:
    cached:
