version: '2.0'

services:
  app:
    build: ./app
    command: >
      sh -cex "
        composer run-script symfony-scripts;
        exec php-fpm;
      "
    env_file: .env
    environment:
        XDEBUG_CONFIG: "remote_host=${XDEBUG_REMOTE_HOST}"
    volumes:
      - ./app:/srv

  web:
    build: ./web
    ports:
      - "${WEB_PORT}:80"
    volumes_from:
      - app

  db:
    image: mariadb:10.1
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - "MYSQL_DATABASE=${DATABASE_NAME}"
      - "MYSQL_USER=${DATABASE_USER}"
      - "MYSQL_PASSWORD=${DATABASE_PASSWORD}"
