version: '2.0'

services:
  app:
    build: ./app
    command: >
      sh -cex "
        composer run-script symfony-scripts;
        bin/console cache:warmup;
        exec php-fpm;
      "
    env_file: .env
    volumes:
      - ./app:/srv
      - vendor:/srv/vendor
      - var:/srv/var

  web:
    build: ./web
    ports:
      - "${WEB_PORT}:80"
    volumes_from:
      - app

  db:
    image: mariadb:10.1
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - "MYSQL_DATABASE=${DATABASE_NAME}"
      - "MYSQL_USER=${DATABASE_USER}"
      - "MYSQL_PASSWORD=${DATABASE_PASSWORD}"

volumes:
  vendor:
  var:
